title: Research Tips and Strategies
description: A collection of tips and strategies to help you get started on your research projects

url: https://dmcwo.github.io/research-tips
baseurl: "/research-tips"
paginate_path: "blog/page:num/"
permalink: :title/

# Collections
collections:
    embeds:
        output: true
        permalink: /embeds/:path/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

# social:
#   github: brianmaierjr
#   twitter: brianmaierjr
#   facebook: brianmaierjr
#   email: brimaidesigns@gmail.com

# google_analytics: "UA-"
