title: "WI+RE"
description: WI+RE (Writing Instruction + Research Education) is a UCLA community focused on helping all learners succeed in their writing and research projects.
author: {
            "@type": "EducationalOrganization",
            "name": "WI+RE",
            "url": "https://uclalibrary.github.io/research-tips/",
            "email": "uclawire@ucla.edu",
            "description": "WI+RE (Writing Instruction + Research Education) is a UCLA community focused on helping all learners succeed in their writing and research projects.",
            "alternateName": "Writing Instruction and Research Education",
            "parentOrganization": "UCLA Library",
            "publishingPrinciples": "https://uclalibrary.github.io/research-tips/about/",
            "award": "ARL Film Festival Best Reflection of Diversity 2018",
            "sameAs": [
               "https://twitter.com/WIREbruin",
               "https://www.facebook.com/WIREbruin"
             ],
            "brand": [
               "UCLA",
               "UCLA Library"
             ]

url: https://uclalibrary.github.io/research-tips
baseurl: "/research-tips"
paginate_path: "blog/page:num/"
permalink: :title/

# Collections
collections:
    embeds:
        output: true
        permalink: /embeds/:path/
    cats:
        output: true
        permalink: /categories/:path/
        
# Defaults
defaults:
  - scope:
      path: ""
      type: cats
    values:
      layout: "category"

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: uclalibrary
   twitter: WIREbruin
   facebook: WIREbruin
#   email: 

# google_analytics: "UA-"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
gems:
- jekyll-seo-tag
- jekyll-paginate
- jekyll-sitemap
